### ISSUE TITLE
Foto anggota tidak muncul di laman utama

### ISSUE THREAD

**Issue by ghost** [akbar-dzikri/cliakad-finals#2]
Saat masuk ke halamanutama, foto foto anggota tidak muncul

# Screenshot
![image](https://github.com/akbar-dzikri/cliakad-finals/assets/161218557/33ed1114-8f70-4bc6-9af0-ecb29548b90b)
![Screenshot from 2024-02-01 12-12-37](https://github.com/akbar-dzikri/cliakad-finals/assets/161218557/b339b0de-285c-44c0-830f-b597c8a3015f)

**Comment by ghost** [comment]
untuk deskripsi kurang lengkap, spesifiknya issue nya gimana ya

**Comment by akbar-dzikri** [comment]
issue sudah selesai, close issue sekarang

![image](https://github.com/akbar-dzikri/cliakad-finals/assets/154778067/8435c113-9f50-401f-b155-f42ba9fdabef)
