### ISSUE TITLE
Foto anggota tidak muncul di laman utama 

### ISSUE THREAD

**Issue by Wahidin27** [akbar-dzikri/cliakad-finals#3]
Saat masuk ke halaman utama,foto foto anggota tidak muncul

# screenshot
![Screenshot_2024-02-25-20-17-12-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/akbar-dzikri/cliakad-finals/assets/161218934/9ed04c72-231a-4ae6-9c71-50e3ecbccd4c)

**Comment by Wahidin27** [comment]
Masalah issues sudah di perbaiki

**Comment by Lukmanul6305** [comment]
lah ini tah?
