### ISSUE TITLE
CONTOH HIMAKOM

### ISSUE THREAD

**Issue by Annurofiq** [akbar-dzikri/cliakad-finals#6]
![download](https://github.com/akbar-dzikri/cliakad-finals/assets/161218892/d2a2fc98-9791-4ac4-9e5f-d23dc8091f93)
![code](https://github.com/akbar-dzikri/cliakad-finals/assets/161218892/58f4c7f6-2a45-47e6-aad9-3e3f48676323)

**Comment by ghost** [comment]
amanannnnn

**Comment by Annurofiq** [comment]
kurang rapih
